name: image_palette_extractor
description: "Flutter plugin to extract the dominant color or a color palette from an image. Perfect for dynamic interfaces such as Spotify."
version: 0.0.1
homepage: https://github.com/DomingoMG/image_palette_extractor
repository: https://github.com/DomingoMG/image_palette_extractor
issue_tracker: https://github.com/DomingoMG/image_palette_extractor/issues

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  image: ^4.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter: